service: default
runtime: nodejs10

# env_variables:
#   POSTGRESQL: "postgresql://bots-user:1234@172.18.176.3:5432/docs"
#   TELEGRAM_TOKEN: "1317427555:AAGgfYe3nThTLrBblrOBroe8Sl68gCVZjic"
#   CLOUD_CONVERT_KEY: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2I3ZGExNmM4YjdiMGJiNWVlNWM5MTAyNzBlMzlmNzdjMDM2YzU4MWI1ODdhYThiMjk2ZjY3MTk2ZWJjN2JmNzYzMDg5YjQ1NzM1MDRkMTAiLCJpYXQiOjE1OTY5NzU0ODYsIm5iZiI6MTU5Njk3NTQ4NiwiZXhwIjo0NzUyNjQ5MDg2LCJzdWIiOiIzODMwNjA0MyIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.k-NxiDb5JhjqfhKEisyRS6ooi3cQD7c9LoSj7lkaMFoPNrci_LOqErGbJrQVk8DtaEyqovtGodvzgRh3Y_0nsX3y9IhwzH34ezv2_RDgMpwjoYLm-qLZBlVBnZ3rVuhqKT9HcHn3DYAc1FRwnLEMjLChy7FXFWmEHx8ytwl-OBcKAgTlmI2H14zWGIef8DvLgYljMLE-PbPXn-kkPW9FJgkh6QmMXHKWTg5VQvB2mum7wNfSFQk0Z7oYeOe17sDOuTopjLVv5SYp2CbrJfPM-3plXzsfNBa-nF4AJ_DSt6yG1BfBk0tho5rldxzjlZW-apblyVUMFxs2XBoEzCynFUjqy7KRmsmpX6HeGNuyECv8M4M9nhfm7kypoLXIimyI6_RtKUrI2KrDrerp2sVJ7b3vs6I-fTMV_roRBPEtjZquhfS4PDTKOeqZPvFjTOrOAYBkgpy8OjTIrS0Q6bDtSotA7qM7GuJ9HpTUmJeu4AAy3lmb3gHWWVne9w9-n_ywMsndCX8Y7sWML6a1MZnvbknHq7HybLGZh3fPYs6MNE3UqgfSUJyTCZ4YX-cx7Ws85F19FTs42CdqsprSqVK_1iqRdQ9lajYB-dgNvzCBhcu8zqz7Y_Ddzh0HTLMVbtz0PxRC8onT7vNqHKJgaamgjdZ1-I-GyHkpFip9sD_zWV8"
#   CLOUD_PROJECT_ID: "docs-bot-287308"
#   CLOUD_STORAGE_BUCKET: "docs-templates-bucket"
#   HEALTH_SERVER: 8080
#   LOCAL_STORAGE: "/tmp"

# TODO: PM2 (Restarting on failure)
# Do NOT build
entrypoint: npm run start

manual_scaling:
  instances: 1

includes:
  - environment.yaml

# Location: europe-west3 (Frankfurt)
